name: CI

on:
  push:
    paths:
      - ".github/**"
      - "app/**"
      - "config/**"
      - "database/**"
      - "resources/**"
      - "routes/**"
      - "tests/**"
jobs:
  laravel-ci:
    name: Build & Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432/5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: cp .env.ci .env
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Generate jwt secret key
      run: php artisan jwt:secret
    - name: Clear config
      run: php artisan optimize:clear
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run migrations and seeders
      run: php artisan migrate:fresh --seed --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: php artisan test --parallel
